Add getSetting and saveSetting functions to database classes
- Added generic getSetting(key) method to LeadDatabase in database.js
- Added generic saveSetting(key, value) method to LeadDatabase in database.js
- Added async getSetting(key) method to LeadDatabase in database-pg.js
- Added async saveSetting(key, value) method to LeadDatabase in database-pg.js
- These functions are used by CRM webhook to store/retrieve webhook URL
- Fixes: TypeError: LeadDatabase.getSetting is not a function